[log]
# DEBUG, INFO, WARNING, ERROR, CRITICAL
level = INFO
path = /monitor/log

[docker]
uri = unix://var/run/docker.sock
debug = 1

[redis]
host = redis
port = 6379

[target_system]
container_name = cdnpixel
network_interface = eth0

[process]
looping_time = 5
channel = channel_process
proc_path = /var/lib/proc
ignored_digest_file = /monitor/monitor/ignored_digest.txt
not_saved_digest_file = /monitor/monitor/not_saved_digest.txt
exe_dir_path = /monitor/monitor/exe

[metric]
metric_cpu_mem_avg_length = 10
metric_network_avg_length = 10